permalink: /:categories/:title.html
url: "//honkimi.github.io/jekyll-masonry/"
full_name: "Rideshare News"
first_name: "Rideshare"
last_name: "News"
blog_title: "Rideshare News "
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "test"
copyright_year: "2014"
google_analytics_code: ""
aboutme: "Something about the author here"
twitter: "kimihom"
github: ""
facebook: ""
linkined_url: ""

BASE_PATH : "//honkimi.github.io/jekyll-masonry/"
